
 sources:
  - name: gz_raw_data
    description: gz_raw_data_source
    tables:
      - name: raw_gz_sales
        description: sales of greenweez 
        tests:
          - unique:
              column_name: "(orders_id||'_'||pdt_id)"
      - name: raw_gz_product
        description: product id of greenweez
        columns: 
          - name: products_id
            description: products_id
            tests:
             - unique
             - not_null  
      - name: raw_gz_ship
        description: orders id for greenweez
        columns: 
          - name: orders_id
            description: products_id
            tests:
             - unique
             - not_null 
      - name: raw_gz_adwords
        identifier: raw_gz_adwords
        description: adwords
        tests:
        - unique:
            column_name: "(date_date || '-' ||  campaign_key)"
        columns:
          - name: date_date
            description: the date of the campaign 
          - name: paid_source
            description: paid source
          - name: campaign_key
            description: campaign_key
          - name: camPGN_name
            description: camPGN_name  
          - name: ads_cost
            description: ads_cost
          - name: impression
            description: impression
          - name: click
            description: click  
      - name: raw_gz_bing
        identifier: raw_gz_bing
        description: bing
        tests:
        - unique:
            column_name: "(date_date || '-' ||  campaign_key)"
        columns:
          - name: date_date
            description: the date of the campaign 
          - name: paid_source
            description: paid source
          - name: campaign_key
            description: campaign_key
          - name: camPGN_name
            description: camPGN_name  
          - name: ads_cost
            description: ads_cost
          - name: impression
            description: impression
          - name: click
            description: click 
      - name: raw_gz_criteo
        identifier: raw_gz_criteo
        description: criteo
        tests:
        - unique:
            column_name: "(date_date || '-' ||  campaign_key)"
        columns:
          - name: date_date
            description: the date of the campaign 
          - name: paid_source
            description: paid source
          - name: campaign_key
            description: campaign_key
          - name: camPGN_name
            description: camPGN_name  
          - name: ads_cost
            description: ads_cost
          - name: impression
            description: impression
          - name: click
            description: click  
      - name: raw_gz_facebook
        identifier: raw_gz_facebook
        description: facebook
        tests:
        - unique:
            column_name: "(date_date || '-' ||  campaign_key)"
        columns:
          - name: date_date
            description: the date of the campaign 
          - name: paid_source
            description: paid source
          - name: campaign_key
            description: campaign_key
          - name: camPGN_name
            description: camPGN_name  
          - name: ads_cost
            description: ads_cost
          - name: impression
            description: impression
          - name: click
            description: click
